<?xml version="1.0" encoding="UTF-8"?>

<!-- 내부 DTD 선언 -->
<!DOCTYPE academy [
	<!ELEMENT acadamy (instructors, students, employees) >
		<!ATTLIST academy location		CDATA #REQUIRED
						  university	CDATA #IMPLIED
						  startDate		CDATA #IMPLIED
						  endDate 		CDATA #IMPLIED >
		<!ELEMENT instructors (intructor)* >
			<!ELEMENT instructor (name, subject*) >
				<ATTLIST instructor gender CDATA #IMPLIED >
				<!ELEMENT name 	  (#PCDATA) >
				<!ELEMENT subject (#PCDATA) >
				
		<!ELEMENT students (student)* >
			<!ELEMENT student (name, address, dwelling) >
				<ATTLIST student major CDATA #IMPLIED >
				<!ELEMENT name 	  (#PCDATA) >
				<!ELEMENT address (#PCDATA) >
				<!ELEMENT dwelling (#PCDATA) >
		<!ELEMENT employees (employee)* >
			<!ELEMENT employee (name, dept, position) >
				<ATTLIST employee major CDATA #IMPLIED >
				<!ELEMENT name 	  (#PCDATA) >
				<!ELEMENT dept (#PCDATA) >
				<!ELEMENT position (#PCDATA) >
		
]>
<!-- XML 선언 -->
<academy location="50436" university="hannamUniversity"
		 startDate="2018-06-25" endDate="2018-08-31">
	<instructors>
		<intructor gender="F">
			<name>채한나</name>
			<subject>SQL, PL/SQL</subject>
			<subject>Java</subject>
			<subject>Servlet/JSP</subject>
		</intructor>
		<intructor gender="M">
			<name>강신철</name>
			<subject>모델링</subject>
		</intructor>
		<intructor gender="F">
			<name>오소진</name>
			<subject>스프링 프레임워크</subject>
			<subject>프로젝트</subject>
		</intructor>
	</instructors>
	<students>
		<student major="GIT">
			<name>유재성</name>
			<address>용운동</address>
			<dwelling>통학</dwelling>
		</student>
		<student>
			<name>윤홍식</name>
			<address>오정동</address>
			<dwelling>자취</dwelling>
		</student>
		<student major="GIT">
			<name>조성철</name>
			<address>오정동</address>
			<dwelling>기숙사</dwelling>
		</student>
		<student major="japan">
			<name>강병우</name>
			<address>사정동</address>
			<dwelling>통학</dwelling>
		</student>
		<student major="CE">
			<name>이동희</name>
			<address>법동</address>
			<dwelling>통학</dwelling>
		</student>
	</students>
	<employees>
		<employee>
			<name>백영현</name>
			<dept>글로벌 IT 경영</dept>
			<position>조교</position>
		</employee>
		<employee>
			<name>박현길</name>
			<dept>이노비즈</dept>
			<position>부장</position>
		</employee>
	</employees>
</academy>